name: Test Deploy With Minifest

# This workflow is triggered on any golang code, makefile, workflow changes to repository.
on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  deploy-by-manifest:
    name: Test Deploy by Manifest
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu24.04]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup KinD Cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          cluster_name: kind
      - name: Deploy by manifest
        run: |
          make deploy-by-manifest
      - name: Test Webhook
        run : |
          set -ex
          kubectl create -f ./config/samples/milvus_minimum.yaml
          kubectl delete -f ./config/samples/milvus_minimum.yaml
          kubectl create -f ./config/samples/milvus_cluster_minimum.yaml
          kubectl delete -f ./config/samples/milvus_cluster_minimum.yaml
